feat: sound manager added
status-im/dotherside pull request #57
Opened 2022-02-10 15:52 UTC by saledjenic

2022-02-10 15:57 UTC, jrainville approved these changes
Looks good.
Just take a look at the indentation if it's not just a diff bug

2022-02-10 15:57 UTC, jrainville commented on lib/src/Status/SoundManager.cpp
> +        }
The indentation looks messed up here

2022-02-11 14:36 UTC, jrainville approved these changes

2022-02-11 20:12 UTC, borismelnik requested changes
Nice work! 
But you know, the best way for playing raw audio is `QSound`(without any instance) or `QSoundEffect` (for a low latency file). 
`QMediaPlayer` needed for playing songs and etc.

2022-02-11 20:12 UTC, borismelnik commented on lib/include/DOtherSide/Status/SoundManager.h
> +        SoundManager &operator=(SoundManager &&) = delete;
You can use just `Q_DISABLE_COPY_MOVE` instead of methods above

2022-02-21 14:14 UTC, borismelnik approved these changes

2022-02-21 17:52 UTC, jrainville approved these changes

2022-02-21 20:26 UTC, merged